<<<<<<< HEAD
version: "3"
services:
  spring-achat:
    image: saifkadri/achat
    ports:
      - "8089:8089"
    networks:
      - net-mysql
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/achatdb
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    volumes:
      -  /home/mysql/saifdata:/var/lib/mysql:rw
    networks:
      - net-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
=======
version: "3"
services:
  spring-achat:
    image: saifkadri/achat
    ports:
      - "8089:8089"
    networks:
      - net-mysql
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/achatdb
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    volumes:
      -  /home/mysql/saifdata:/var/lib/mysql:rw
    networks:
      - net-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
>>>>>>> b285f3343fab74367a585524cb0e3c8818b15d43
   